name: Update Stats
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch stats
        run: |
          gh api repos/${{ github.repository }} --jq '{stars:.stargazers_count,forks:.forks_count,issues:.open_issues_count}' > stats.json || true
          echo "# Stats" > STATS.md
          if [ -f stats.json ]; then cat stats.json >> STATS.md; fi
          git config user.name "github-actions[bot]" || true
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com" || true
          git add STATS.md || true
          git commit -m "ci: update STATS.md [skip ci]" || true
          git push || true
